name: Obtiene el estado de las votaciones
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Fetch data
        run: 'node stats.mjs'

      - name: Commit files
        run: |
          git config --local user.email "actions@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add stats.txt
          git commit -m "Añade datos"

      - name: Hace push
        uses: ad-m/github-push-action@master
